branch-defaults:
  master:
    environment: RailsDeployingApp-dev
    group_suffix: null
environment-defaults:
  RailsDeployingApp-de:
    branch: null
    repository: null
global:
  application_name: RailsDeployingApp
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.6 (Puma)
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
